name: Post Webhook
on:
  # schedule:
  #   - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  post_webhook:
    runs-on: ubuntu-latest
    name: Post Webhook
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup a Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Webhook
        id: rss
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          STREAMER_USERNAME: ${{ secrets.STREAMER_USERNAME }}
          IGNORED_CATEGORIES: ${{ secrets.IGNORED_CATEGORIES }}
        run: python src/main.py
      - name: Check if there is any new translations
        id: verify_diff
        run: |
          git diff --quiet sent.txt || echo "::set-output name=new_translations_exist::true"
      - name: Commit files
        if: steps.verify_diff.outputs.new_translations_exist == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Updated sent.txt"
          git push
